# Generated by Django 2.0.5 on 2018-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180522_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(to='polls.Category'),
        ),
    ]
